In [ ]:
import numpy as np

### Array Creation

In [ ]:
a = np.array([1, 2, 3])        # Creates a 1D NumPy array from a list
b = np.arange(5)               # 0 to 4
c = np.zeros((2, 3))           # 2x3 matrix of 0s
d = np.ones(4)                 # 1D array of 1s
e = np.eye(3)                  # a 3x3 identity matrix
f = np.random.randn(3, 4)      # Creates a 3x4 array of random numbers from standard normal distribution (mean=0, std=1)

In [ ]:
print("3x3 Identity Matrix:\n", e)

3x3 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Array Properties

In [ ]:
print(a.shape, a.dtype, a.ndim, a.size)

(3,) int64 1 3


### Indexing & Slicing

In [ ]:
arr = np.arange(10)
print(arr[2:7])     # slice
print(arr[::-1])    # reverse

[2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]


### Element-wise Operations

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print(x + y)
print(x * y)
print(np.sqrt(x))

[11 22 33]
[10 40 90]
[1.         1.41421356 1.73205081]


### Mini Task: Create a 1D array from 0 to 30 with step 2 and reshape it to a 2D array

In [ ]:
array_step = np.arange(0, 31, 2)
reshaped_array = array_step.reshape(4, 4)
print("1D Array from 0 to 30 with step 2:", array_step)
print("Reshaped to 2D (4x4):", reshaped_array)

1D Array from 0 to 30 with step 2: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
Reshaped to 2D (4x4): [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


### Reshaping and Aggregation

In [ ]:
a = np.arange(6).reshape(2, 3)
print(a)
b = np.array([1, 0, 1])
print(a + b)  # Adds b to each row of a

[[0 1 2]
 [3 4 5]]
[[1 1 3]
 [4 4 6]]


In [ ]:
print(a.sum(), a.mean(), a.std())
print(a.sum(axis=0))  # column-wise sum

15 2.5 1.707825127659933
[3 5 7]


Practice:
- Create a 3x3 matrix of random numbers
- Find its row-wise max and min

In [ ]:
# Create a 3x3 matrix of random numbers
random_matrix = np.random.randn(3, 3)
print("Random 3x3 matrix:\n", random_matrix)

# Find row-wise max
row_max = random_matrix.max(axis=1)
print("\nRow-wise max:", row_max)

# Find row-wise min
row_min = random_matrix.min(axis=1)
print("Row-wise min:", row_min)


Random 3x3 matrix:
 [[ 8.65922763e-01  8.85737551e-01  1.25202466e+00]
 [ 1.34316088e-01  6.68877741e-01  7.35362551e-05]
 [-2.93304907e-02  7.92827593e-01 -7.31696131e-01]]

Row-wise max: [1.25202466 0.66887774 0.79282759]
Row-wise min: [ 8.65922763e-01  7.35362551e-05 -7.31696131e-01]


Quiz
1. What is the shape of `np.arange(12).reshape(3, 4)`?
2. Given `a = np.array([10, 20, 30])`, what is the output of `a > 15`?

In [ ]:
a = np.array([10, 20, 30])
print(a > 15)

[False  True  True]
